version: "3"

services:
  garbled-api:
    build:
      context: garbled_api
    ports:
      - "8080:8080"
  garbled-ui:
    build:
      context: garbled-ui
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - garbled-api
    links:
      - garbled-api
